version: '3.8'

services:
  app:
    build: .
    container_name: simpleapp_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - simpleapp_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:fjZl7+txXedmuXyFzDHmFoSWTOCnn98H2w2zZPpvBw8=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: simpleapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Configura la contraseña del usuario root
      MYSQL_DATABASE: laravel    # Crea la base de datos laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - simpleapp_network

  nginx:
    image: nginx:latest
    container_name: simpleapp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - simpleapp_network

networks:
  simpleapp_network:

volumes:
  db_data: